name: Job
version: '1.0-SNAPSHOT'
main: org.job.job.Job
api-version: '1.20'

commands:
  changejob:
    description: 직업 변경 GUI를 엽니다.
    usage: /changejob
  job:
    description: 직업 관련 명령어를 실행합니다.
    usage: /job <skill|toggle>
  cook:
    description: 요리 GUI를 엽니다.
    usage: /cook <도구>